[package]
name = "muginn-compile"
version = "0.8.1"
edition.workspace = true
license.workspace = true

[dependencies]
muginn-core = { path = "../core" }
muginn-store = { path = "../store" }
muginn-verify = { path = "../verify" }
serde_json = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
bytecite = { path = "../bytecite" }
tempfile = "3"
