[package]
name = "muginn-cli"
version = "0.8.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "muginn"
path = "src/main.rs"

[dependencies]
muginn-core = { path = "../core" }
bytecite = { path = "../bytecite" }
muginn-adapters = { path = "../adapters" }
muginn-select = { path = "../select" }
muginn-store = { path = "../store" }
muginn-verify = { path = "../verify" }
muginn-render = { path = "../render" }
muginn-vault = { path = "../vault" }
muginn-compile = { path = "../compile" }
muginn-server = { path = "../server" }
muginn-eval = { path = "../eval" }
serde_json = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
dirs-next = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
tempfile = "3"
